// src/features/settings/solid-context.tsx
/** @jsxImportSource solid-js */

import type { JSX } from "solid-js";
import { createContext, useContext } from "solid-js";
import type { SettingsReader } from "./types";

const SolidSettingsContext = createContext<SettingsReader>();

export function useSolidSettings(): SettingsReader {
  const ctx = useContext(SolidSettingsContext);
  if (!ctx) {
    throw new Error(
      "useSolidSettings must be used within SolidSettingsProvider",
    );
  }
  return ctx;
}

export function SolidSettingsProvider(props: {
  value: SettingsReader;
  children: JSX.Element;
}) {
  return (
    <SolidSettingsContext.Provider value={props.value}>
      {props.children}
    </SolidSettingsContext.Provider>
  );
}

// src/features/settings/context.tsx
import { createContext, type ReactNode, useContext } from "react";
import type { SettingsReader } from "./types";

const SettingsContext = createContext<SettingsReader | null>(null);

export function useSettings(): SettingsReader {
  const ctx = useContext(SettingsContext);
  if (!ctx) {
    throw new Error("useSettings must be used within SettingsProvider");
  }
  return ctx;
}

export function SettingsProvider({
  value,
  children,
}: {
  value: SettingsReader;
  children: ReactNode;
}) {
  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
}
